---
- name: Installation main
  hosts: all
  become: yes
  
  tasks:
    - include: docker_deploy.yaml
    - include: ufw_Ann.yaml
    - include: webserver_Ann.yaml
    - include: samba.yaml
    - include: backup2VM.yaml  