---
- name: Installation main
  hosts: all
  become: yes

  - include_tasks: docker_deploy.yaml
  - include_tasks: ufw_Ann.yaml
  - include_tasks: webserver_Ann.yaml
  - include_tasks: samba.yaml
  - include tasks: backup2VM.yaml  