---
- name: Example playbook
  hosts: target_hosts
  become: yes

  vars:
    variable1: value1
    variable2: value2
  tasks:
  - name: Task 1
    <task_definition>
  - name: Task 2
    <task_definition>
  handlers:
  - name: Handler 1
    <handler_definition>
  - name: Handler 2
    <handler_definition>