---
- name: Setup
  hosts: MainVM
  become: true
  tasks:

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: ensure docker is at the latest version
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - curl
          - docker
          - virtualenv
          - python3-pip
          - python3-setuptools
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: deploy docker
      docker_container:
        name: Nextcloud
        image: nextcloud
        ports:
          - "8080:80"
          - "8443:443"
        volumes:
          - nextcloud:/var/www/html
          - /nc_data:/var/www/html/data
        restart_policy: always

- name: Install and Setup Firewall
  hosts: all
  become: true
  tasks:
    - name: Outgoing allow
      community.general.ufw:
        state: enabled
        direction: outgoing
        policy: allow
    - name: Incoming deny
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny
    - name: Allow SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp
    - name: Allow HTTP
      ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Allow HTTPS from Nextcloud-container #Toegevoegd om gepubliceerde poorten van Nextcloud door te laten
      ufw:
        rule: allow
        port: "8443"
        proto: tcp
    - name: Allow HTTP from Nextcloud-container #Toegevoegd om gepubliceerde poorten van Nextcloud door te laten
      ufw:
        rule: allow
        port: "8080"
        proto: tcp
    - name: Allow Ports for SMB-protocol #Toegevoegd om SAMBA-protocol te faciliteren voor folder op DataVM
      ufw:
        rule: allow
        port: "445"
        proto: tcp
    - name: Allow Ports for SMB-protocol #Toegevoegd om SAMBA-protocol te faciliteren voor folder op DataVM
      ufw:
        rule: allow
        port: "139"
        proto: tcp
    - name: Enable ufw
      community.general.ufw:
        state: enabled

- name: Install and configure Samba-share on DataVM
  hosts: DataVM
  become: yes
  tasks:
    - name: Creates directory
      file:
        path: /nc_data
        state: directory
    - name: Install Samba
      apt:
        name: samba
        state: latest
        update_cache: true
    - name: Create Samba configuration file
      copy:
        dest: /etc/samba/smb.conf
        content: |
          [global]
          workgroup = WORKGROUP
          security = user
          [share]
          path = /nc_data
          read only = no
          guest ok = yes
    - name: Restart Samba service
      service:
        name: smbd
        state: restarted

- name: Cronjob to BackupVM
  hosts: DataVM
  become: yes
  tasks:
  - name: Run a command and register its output as a variable
    ansible.builtin.debug:
      var: "{{ hostvars['BackupVM'].ansible_default_ipv4.address }}"
    register: ip_address
    ignore_errors: true
  - name: Create a task to run every day at 22u to copy the nextcloud data-folder to the backup-VM
    cron:
      name: "Setup stand-alone backup-task (Mirror)"
      minute: "0"
      hour: "22"
      job: "rsync -ahvAE --delete /nc_data ubuntu@{{ ip_address }}:/nc_data_backup "