---
- name: install mariadb
  hosts: localhost
  become: true
  tasks:
    - name: install mariadb server
      apt:
        name: mariadb-server
        state: latest
    - name: install mariadb client
      apt:
        name: mariadb-client
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes