---
- name: install mariadb
  hosts: localhost
  become: true
  tasks:
    - name: install mariadb server
      apt:
        name: mariadb-server
        state: latest
    - name: install mariadb client
      apt:
        name: mariadb-client
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: test mysql_secure_installation
      mysql_secure_installation:
        login_password: Ann
        new_password: password22
        user: root
        login_host: localhost
        hosts:
         - localhost
         - 127.0.0.1
         - ::1
        change_root_password: true
        remove_anonymous_user: true
        disallow_root_login_remotely: true
        remove_test_db: true
      register: mysql_secure