--- 
- name: Install PHP 8.1
  hosts: localhost
  become: true
  tasks: 
    - name: Installation properties
      apt:
        name: software-properties-common
        state: present
    - name: Installation repository
      apt_repository:
        validate_certs: no
        repo: ppa:ondrej/php
        state: present
    -  name: Installation PHP 8.1
       apt:
         name: php8.1
         state: present
    - name: Install packages
      apt:
        pkg:
          - php8.1-common
          - php8.1-pgsql
	  - php8.1-fpm
	  - php8.1-bz2
	  - php8.1-intl
	  - php8.1-bcmath
	  - php8.1-gmp
          - php8.1-mysql
          - php8.1-xml
          - php8.1-xmlrpc
          - php8.1-curl
          - php8.1-gd
          - php8.1-imagick
          - php8.1-cli
          - php8.1-dev
          - php8.1-imap
          - php8.1-mbstring
          - php8.1-opcache
          - php8.1-soap
          - php8.1-zip
          - php8.1-redis
          - php8.1-intl
        state: present
        update_cache: yes
    - name: start PHP 8.1
      service: 
        name: php8.1-fpm
        state: started
        enabled: yes